"""Base monitoring framework for ATLAS - proactive alerts and system awareness."""

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import List, Optional
import logging

logger = logging.getLogger("atlas.monitoring")


class AlertSeverity(Enum):
    """Alert severity levels."""
    INFO = "info"
    WARNING = "warning"
    URGENT = "urgent"


@dataclass
class Alert:
    """An alert generated by a monitor."""
    monitor_name: str
    severity: AlertSeverity
    message: str
    action_suggestion: Optional[str] = None
    timestamp: datetime = field(default_factory=datetime.now)
    data: dict = field(default_factory=dict)

    def format_butler_message(self) -> str:
        """Format the alert as a butler-style message.

        Returns:
            Formatted message string
        """
        prefix = {
            AlertSeverity.INFO: "Sir, I noticed that",
            AlertSeverity.WARNING: "Sir, I should mention that",
            AlertSeverity.URGENT: "Sir, I must bring to your attention that",
        }[self.severity]

        message = f"{prefix} {self.message}"

        if self.action_suggestion:
            message += f"\n\n{self.action_suggestion}"

        return message


class Monitor(ABC):
    """Abstract base class for monitors."""

    name: str = "base"
    check_interval: int = 300  # seconds between checks

    def __init__(self, enabled: bool = True, **config):
        """Initialize monitor.

        Args:
            enabled: Whether this monitor is active
            **config: Additional configuration
        """
        self.enabled = enabled
        self.config = config
        self._last_check = None
        self._last_alerts = []

    @abstractmethod
    async def check(self) -> List[Alert]:
        """Perform a monitoring check.

        Returns:
            List of alerts (empty if nothing to report)
        """
        raise NotImplementedError("Subclasses must implement check()")

    def should_check(self) -> bool:
        """Determine if enough time has passed for another check.

        Returns:
            True if should run check
        """
        if not self.enabled:
            return False

        if self._last_check is None:
            return True

        elapsed = (datetime.now() - self._last_check).total_seconds()
        return elapsed >= self.check_interval

    async def run_check(self) -> List[Alert]:
        """Run a check if it's time.

        Returns:
            List of alerts, or empty list if check skipped
        """
        if not self.should_check():
            return []

        try:
            alerts = await self.check()
            self._last_check = datetime.now()
            self._last_alerts = alerts
            return alerts
        except Exception as e:
            logger.error(f"Monitor {self.name} check failed: {e}")
            return []

    def get_status(self) -> dict:
        """Get monitor status.

        Returns:
            Status dictionary
        """
        return {
            "name": self.name,
            "enabled": self.enabled,
            "last_check": self._last_check.isoformat() if self._last_check else None,
            "last_alert_count": len(self._last_alerts),
            "check_interval": self.check_interval,
        }


class MonitorManager:
    """Manages multiple monitors and aggregates alerts."""

    def __init__(self):
        """Initialize the monitor manager."""
        self.monitors: List[Monitor] = []
        self._alert_history: List[Alert] = []
        self._max_history = 100

    def register(self, monitor: Monitor) -> None:
        """Register a monitor.

        Args:
            monitor: Monitor instance to register
        """
        self.monitors.append(monitor)
        logger.info(f"Registered monitor: {monitor.name}")

    def unregister(self, monitor_name: str) -> bool:
        """Unregister a monitor by name.

        Args:
            monitor_name: Name of monitor to remove

        Returns:
            True if found and removed
        """
        for i, m in enumerate(self.monitors):
            if m.name == monitor_name:
                del self.monitors[i]
                return True
        return False

    async def check_all(self) -> List[Alert]:
        """Run all monitors and collect alerts.

        Returns:
            List of all alerts from all monitors
        """
        all_alerts = []

        for monitor in self.monitors:
            try:
                alerts = await monitor.run_check()
                all_alerts.extend(alerts)
            except Exception as e:
                logger.error(f"Error running monitor {monitor.name}: {e}")

        # Store in history
        for alert in all_alerts:
            self._alert_history.append(alert)
            if len(self._alert_history) > self._max_history:
                self._alert_history.pop(0)

        return all_alerts

    def get_urgent_alerts(self) -> List[Alert]:
        """Get any urgent alerts from recent checks.

        Returns:
            List of urgent alerts
        """
        return [
            a for a in self._alert_history
            if a.severity == AlertSeverity.URGENT
            and (datetime.now() - a.timestamp).total_seconds() < 3600
        ]

    def get_status(self) -> dict:
        """Get status of all monitors.

        Returns:
            Status dictionary
        """
        return {
            "monitors": [m.get_status() for m in self.monitors],
            "total_alerts_in_history": len(self._alert_history),
            "urgent_alerts": len(self.get_urgent_alerts()),
        }
