"""Spec Generator for ATLAS.

Generates requirements.md, design.md, and tasks.md files using AI.
"""

import os
from typing import Optional
from pathlib import Path

from .models import (
    Spec, Requirement, RequirementType, Priority,
    AcceptanceCriteria, DesignDoc, DesignComponent,
    TaskList, Task, TaskStatus
)


# Templates for spec files
REQUIREMENTS_TEMPLATE = """# Requirements: {name}

## Overview

{description}

## User Stories & Requirements

{requirements}

---

*Generated by ATLAS using EARS (Easy Approach to Requirements Syntax)*
*Last updated: {timestamp}*
"""

DESIGN_TEMPLATE = """# Design: {name}

{design_content}

---

*Generated by ATLAS*
*Last updated: {timestamp}*
"""

TASKS_TEMPLATE = """# Implementation Tasks: {name}

{tasks_content}

---

*Generated by ATLAS*
*Last updated: {timestamp}*
"""


class SpecGenerator:
    """Generates spec files for projects."""

    def __init__(self, openai_api_key: Optional[str] = None):
        """Initialize the generator.

        Args:
            openai_api_key: OpenAI API key for AI-powered generation
        """
        self.openai_api_key = openai_api_key or os.environ.get("OPENAI_API_KEY")

    async def generate_from_idea(
        self,
        idea: str,
        context: Optional[dict] = None,
    ) -> Spec:
        """Generate a complete spec from an idea description.

        Args:
            idea: Natural language description of the project/feature
            context: Optional context (features, constraints, etc.)

        Returns:
            Complete Spec object
        """
        # Use AI to generate the spec if available
        if self.openai_api_key:
            return await self._generate_with_ai(idea, context)

        # Fallback to template-based generation
        return self._generate_from_template(idea, context)

    async def _generate_with_ai(
        self,
        idea: str,
        context: Optional[dict] = None,
    ) -> Spec:
        """Generate spec using AI."""
        try:
            from openai import AsyncOpenAI

            client = AsyncOpenAI(api_key=self.openai_api_key)

            # Build the prompt
            context_str = ""
            if context:
                if context.get("features"):
                    context_str += f"\nFeatures requested:\n" + "\n".join(f"- {f}" for f in context["features"])
                if context.get("technical"):
                    context_str += f"\nTechnical requirements: {context['technical']}"
                if context.get("constraints"):
                    context_str += f"\nConstraints: {context['constraints']}"

            prompt = f"""Analyze this project idea and generate structured specifications:

PROJECT IDEA: {idea}
{context_str}

Generate a JSON response with:
1. requirements: Array of requirements in EARS format, each with:
   - id: REQ-001 format
   - title: Short title
   - description: EARS format requirement (e.g., "When user clicks login, the system shall authenticate credentials")
   - type: one of [ubiquitous, event_driven, state_driven, optional, complex]
   - priority: one of [critical, high, medium, low]
   - user_story: "As a <role>, I want <goal>, so that <benefit>"
   - acceptance_criteria: Array of {{id: "AC-001", description: "..."}}

2. design:
   - overview: High-level description
   - architecture: Technical architecture description
   - components: Array of {{name, description, responsibilities: [], interfaces: []}}
   - data_model: Database/data structure description
   - api_design: API endpoints if applicable
   - error_handling: Error handling strategy
   - testing_strategy: Testing approach

3. tasks: Array of implementation tasks, each with:
   - id: TASK-001 format
   - title: Short title
   - description: What needs to be done
   - priority: one of [critical, high, medium, low]
   - requirement_ids: Array of related requirement IDs
   - files_to_modify: Array of file paths
   - estimated_effort: Time estimate

Return valid JSON only, no markdown."""

            response = await client.chat.completions.create(
                model="gpt-4o-mini",
                messages=[
                    {"role": "system", "content": "You are a requirements engineer. Generate structured specifications in JSON format."},
                    {"role": "user", "content": prompt}
                ],
                temperature=0.7,
                response_format={"type": "json_object"}
            )

            import json
            data = json.loads(response.choices[0].message.content)

            # Parse requirements
            requirements = []
            for req_data in data.get("requirements", []):
                ac_list = [
                    AcceptanceCriteria(id=ac["id"], description=ac["description"])
                    for ac in req_data.get("acceptance_criteria", [])
                ]
                req = Requirement(
                    id=req_data["id"],
                    title=req_data["title"],
                    description=req_data["description"],
                    type=RequirementType(req_data.get("type", "ubiquitous")),
                    priority=Priority(req_data.get("priority", "medium")),
                    user_story=req_data.get("user_story", ""),
                    acceptance_criteria=ac_list,
                )
                requirements.append(req)

            # Parse design
            design_data = data.get("design", {})
            components = [
                DesignComponent(
                    name=c["name"],
                    description=c.get("description", ""),
                    responsibilities=c.get("responsibilities", []),
                    interfaces=c.get("interfaces", []),
                )
                for c in design_data.get("components", [])
            ]
            design = DesignDoc(
                title=f"Design: {idea[:50]}",
                overview=design_data.get("overview", ""),
                architecture=design_data.get("architecture", ""),
                components=components,
                data_model=design_data.get("data_model", ""),
                api_design=design_data.get("api_design", ""),
                error_handling=design_data.get("error_handling", ""),
                testing_strategy=design_data.get("testing_strategy", ""),
            )

            # Parse tasks
            tasks = []
            for task_data in data.get("tasks", []):
                task = Task(
                    id=task_data["id"],
                    title=task_data["title"],
                    description=task_data["description"],
                    priority=Priority(task_data.get("priority", "medium")),
                    requirement_ids=task_data.get("requirement_ids", []),
                    files_to_modify=task_data.get("files_to_modify", []),
                    estimated_effort=task_data.get("estimated_effort", ""),
                )
                tasks.append(task)

            task_list = TaskList(title=f"Tasks: {idea[:50]}", tasks=tasks)

            return Spec(
                name=idea[:100],
                description=idea,
                requirements=requirements,
                design=design,
                tasks=task_list,
            )

        except Exception as e:
            print(f"[SpecGenerator] AI generation failed: {e}")
            return self._generate_from_template(idea, context)

    def _generate_from_template(
        self,
        idea: str,
        context: Optional[dict] = None,
    ) -> Spec:
        """Generate spec using templates (fallback)."""
        # Create basic requirements from context
        requirements = []
        features = context.get("features", []) if context else []

        for i, feature in enumerate(features, 1):
            req = Requirement(
                id=f"REQ-{i:03d}",
                title=feature[:50],
                description=f"The system shall {feature.lower()}",
                type=RequirementType.UBIQUITOUS,
                priority=Priority.MEDIUM,
                acceptance_criteria=[
                    AcceptanceCriteria(
                        id=f"AC-{i:03d}-01",
                        description=f"Verify that {feature.lower()} works correctly"
                    )
                ],
            )
            requirements.append(req)

        # Create basic design
        design = DesignDoc(
            title=f"Design: {idea[:50]}",
            overview=idea,
            architecture="To be defined based on requirements analysis.",
            testing_strategy="Unit tests for core functionality, integration tests for APIs.",
        )

        # Create basic tasks
        tasks = []
        tasks.append(Task(
            id="TASK-001",
            title="Project Setup",
            description="Initialize project structure and dependencies",
            priority=Priority.HIGH,
        ))

        for i, req in enumerate(requirements, 2):
            tasks.append(Task(
                id=f"TASK-{i:03d}",
                title=f"Implement {req.title}",
                description=f"Implement functionality for: {req.description}",
                requirement_ids=[req.id],
                priority=req.priority,
            ))

        tasks.append(Task(
            id=f"TASK-{len(tasks)+1:03d}",
            title="Testing & Documentation",
            description="Write tests and documentation",
            priority=Priority.MEDIUM,
        ))

        task_list = TaskList(title=f"Tasks: {idea[:50]}", tasks=tasks)

        return Spec(
            name=idea[:100],
            description=idea,
            requirements=requirements,
            design=design,
            tasks=task_list,
        )

    def write_spec_files(
        self,
        spec: Spec,
        output_dir: str,
        create_kiro_structure: bool = True,
    ) -> dict:
        """Write spec files to disk.

        Args:
            spec: The spec to write
            output_dir: Base output directory
            create_kiro_structure: If True, create .kiro/specs/ structure

        Returns:
            Dict with file paths
        """
        from datetime import datetime

        base_path = Path(output_dir)

        if create_kiro_structure:
            # Create .kiro/specs/feature-name/ structure
            spec_name = spec.name.lower().replace(" ", "-")[:30]
            spec_name = "".join(c for c in spec_name if c.isalnum() or c == "-")
            spec_dir = base_path / ".kiro" / "specs" / spec_name
        else:
            spec_dir = base_path / "specs"

        spec_dir.mkdir(parents=True, exist_ok=True)

        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")
        files_written = {}

        # Write requirements.md
        requirements_md = ""
        for req in spec.requirements:
            requirements_md += req.to_markdown()

        requirements_content = REQUIREMENTS_TEMPLATE.format(
            name=spec.name,
            description=spec.description,
            requirements=requirements_md,
            timestamp=timestamp,
        )
        req_path = spec_dir / "requirements.md"
        req_path.write_text(requirements_content)
        files_written["requirements"] = str(req_path)

        # Write design.md
        if spec.design:
            design_content = DESIGN_TEMPLATE.format(
                name=spec.name,
                design_content=spec.design.to_markdown(),
                timestamp=timestamp,
            )
            design_path = spec_dir / "design.md"
            design_path.write_text(design_content)
            files_written["design"] = str(design_path)

        # Write tasks.md
        if spec.tasks:
            tasks_content = TASKS_TEMPLATE.format(
                name=spec.name,
                tasks_content=spec.tasks.to_markdown(),
                timestamp=timestamp,
            )
            tasks_path = spec_dir / "tasks.md"
            tasks_path.write_text(tasks_content)
            files_written["tasks"] = str(tasks_path)

        return {
            "spec_dir": str(spec_dir),
            "files": files_written,
            "spec": spec.to_dict(),
        }
