"""Spec Generator for ATLAS.

Generates requirements.md, design.md, and tasks.md files using AI.
"""

import os
from typing import Optional
from pathlib import Path

from .models import (
    Spec, Requirement, RequirementType, Priority,
    AcceptanceCriteria, DesignDoc, DesignComponent,
    TaskList, Task, TaskStatus
)


# Templates for spec files
REQUIREMENTS_TEMPLATE = """# Requirements: {name}

## Overview

{description}

## User Stories & Requirements

{requirements}

---

*Generated by ATLAS using EARS (Easy Approach to Requirements Syntax)*
*Last updated: {timestamp}*
"""

DESIGN_TEMPLATE = """# Design: {name}

{design_content}

---

*Generated by ATLAS*
*Last updated: {timestamp}*
"""

TASKS_TEMPLATE = """# Implementation Tasks: {name}

{tasks_content}

---

*Generated by ATLAS*
*Last updated: {timestamp}*
"""


class SpecGenerator:
    """Generates spec files for projects."""

    def __init__(self, openai_api_key: Optional[str] = None):
        """Initialize the generator.

        Args:
            openai_api_key: OpenAI API key for AI-powered generation
        """
        self.openai_api_key = openai_api_key or os.environ.get("OPENAI_API_KEY")

    async def generate_from_idea(
        self,
        idea: str,
        context: Optional[dict] = None,
    ) -> Spec:
        """Generate a complete spec from an idea description.

        Args:
            idea: Natural language description of the project/feature
            context: Optional context (features, constraints, etc.)

        Returns:
            Complete Spec object
        """
        # Use AI to generate the spec if available
        if self.openai_api_key:
            return await self._generate_with_ai(idea, context)

        # Fallback to template-based generation
        return self._generate_from_template(idea, context)

    async def _generate_with_ai(
        self,
        idea: str,
        context: Optional[dict] = None,
    ) -> Spec:
        """Generate spec using AI with two-phase approach.

        Phase 1: Analyze the idea and determine what structure fits
        Phase 2: Generate the spec using that structure
        """
        try:
            from openai import AsyncOpenAI

            client = AsyncOpenAI(api_key=self.openai_api_key)

            # Build context string from any provided context
            context_str = ""
            if context:
                if context.get("features"):
                    context_str += f"\nFeatures requested:\n" + "\n".join(f"- {f}" for f in context["features"])
                if context.get("technical"):
                    context_str += f"\nTechnical requirements: {context['technical']}"
                if context.get("constraints"):
                    context_str += f"\nConstraints: {context['constraints']}"

            # ============================================
            # PHASE 1: Analyze what this project needs
            # ============================================
            analysis_prompt = f"""Analyze this project idea and determine the best way to spec it out.

PROJECT IDEA: {idea}
{context_str}

Answer these questions in JSON:
{{
    "project_nature": "What kind of thing is this? (e.g., 'printable PDF', 'mobile app', 'REST API', 'ebook', 'CLI tool', 'website', 'physical product', etc.)",
    "deliverables": ["List each concrete thing that needs to be created"],
    "structure_type": "What structure fits best? One of: 'pages' (for printables/documents), 'features' (for software), 'chapters' (for books), 'endpoints' (for APIs), 'screens' (for apps), 'components' (for libraries)",
    "key_elements": ["List the specific elements mentioned in the idea that MUST be included"],
    "is_software": true/false,
    "suggested_sections": ["What sections should the spec have? Be specific to THIS project"]
}}

Be specific to THIS idea. Don't add generic elements that weren't requested."""

            analysis_response = await client.chat.completions.create(
                model="gpt-4o-mini",
                messages=[
                    {"role": "system", "content": "You are a project analyst. Analyze ideas to determine the best structure for specifying them. Be concise and specific."},
                    {"role": "user", "content": analysis_prompt}
                ],
                temperature=0.3,
                response_format={"type": "json_object"}
            )

            import json
            analysis = json.loads(analysis_response.choices[0].message.content)

            # ============================================
            # PHASE 2: Generate spec based on analysis
            # ============================================
            structure_type = analysis.get("structure_type", "features")
            deliverables = analysis.get("deliverables", [])
            key_elements = analysis.get("key_elements", [])
            is_software = analysis.get("is_software", True)
            project_nature = analysis.get("project_nature", "project")

            generation_prompt = f"""Generate a specification for this project based on the analysis.

PROJECT IDEA: {idea}

ANALYSIS:
- Nature: {project_nature}
- Structure type: {structure_type}
- Key elements to include: {', '.join(key_elements)}
- Deliverables: {', '.join(deliverables)}
- Is software: {is_software}

Generate a JSON spec with:

1. "requirements": Array of requirements. Each requirement should be one of the KEY ELEMENTS or DELIVERABLES identified above. Format:
   - id: REQ-001 format
   - title: Name of this deliverable/element (use the exact names from key_elements)
   - description: What this specific item needs to include
   - type: "ubiquitous"
   - priority: "critical", "high", "medium", or "low"
   - user_story: "As a user, I want [this element], so that [benefit]"
   - acceptance_criteria: Array of {{id: "AC-001", description: "specific measurable criterion"}}

2. "design":
   - overview: Brief description of the overall {project_nature}
   - architecture: How the {structure_type} are organized
   - components: Array matching each requirement {{name, description, responsibilities: [], interfaces: []}}
   - data_model: {"Content structure" if not is_software else "Data structures needed"}
   - api_design: {None if not is_software else "API design if applicable"}
   - error_handling: {None if not is_software else "Error handling approach"}
   - testing_strategy: How to verify quality

3. "tasks": Array of tasks to create each deliverable:
   - id: TASK-001 format
   - title: "Create [deliverable name]"
   - description: What to create
   - priority: "critical", "high", "medium", or "low"
   - requirement_ids: [related REQ IDs]
   - files_to_modify: [output file names]
   - estimated_effort: time estimate

IMPORTANT:
- Create requirements ONLY for the key_elements and deliverables listed above
- Do NOT add generic elements that weren't in the original idea
- Each key_element should become exactly one requirement

Return valid JSON only."""

            response = await client.chat.completions.create(
                model="gpt-4o-mini",
                messages=[
                    {"role": "system", "content": f"You are a specification writer for {project_nature} projects. Generate precise specs that match exactly what was requested - nothing more, nothing less."},
                    {"role": "user", "content": generation_prompt}
                ],
                temperature=0.5,
                response_format={"type": "json_object"}
            )

            import json
            data = json.loads(response.choices[0].message.content)

            # Parse requirements
            requirements = []
            for req_data in data.get("requirements", []):
                ac_list = [
                    AcceptanceCriteria(id=ac["id"], description=ac["description"])
                    for ac in req_data.get("acceptance_criteria", [])
                ]
                req = Requirement(
                    id=req_data["id"],
                    title=req_data["title"],
                    description=req_data["description"],
                    type=RequirementType(req_data.get("type", "ubiquitous")),
                    priority=Priority(req_data.get("priority", "medium")),
                    user_story=req_data.get("user_story", ""),
                    acceptance_criteria=ac_list,
                )
                requirements.append(req)

            # Parse design
            design_data = data.get("design", {})
            components = [
                DesignComponent(
                    name=c["name"],
                    description=c.get("description", ""),
                    responsibilities=c.get("responsibilities", []),
                    interfaces=c.get("interfaces", []),
                )
                for c in design_data.get("components", [])
            ]
            design = DesignDoc(
                title=f"Design: {idea[:50]}",
                overview=design_data.get("overview", ""),
                architecture=design_data.get("architecture", ""),
                components=components,
                data_model=design_data.get("data_model", ""),
                api_design=design_data.get("api_design", ""),
                error_handling=design_data.get("error_handling", ""),
                testing_strategy=design_data.get("testing_strategy", ""),
            )

            # Parse tasks
            tasks = []
            for task_data in data.get("tasks", []):
                task = Task(
                    id=task_data["id"],
                    title=task_data["title"],
                    description=task_data["description"],
                    priority=Priority(task_data.get("priority", "medium")),
                    requirement_ids=task_data.get("requirement_ids", []),
                    files_to_modify=task_data.get("files_to_modify", []),
                    estimated_effort=task_data.get("estimated_effort", ""),
                )
                tasks.append(task)

            task_list = TaskList(title=f"Tasks: {idea[:50]}", tasks=tasks)

            return Spec(
                name=idea[:100],
                description=idea,
                requirements=requirements,
                design=design,
                tasks=task_list,
            )

        except Exception as e:
            print(f"[SpecGenerator] AI generation failed: {e}")
            return self._generate_from_template(idea, context)

    def _generate_from_template(
        self,
        idea: str,
        context: Optional[dict] = None,
    ) -> Spec:
        """Generate spec using templates (fallback)."""
        # Create basic requirements from context
        requirements = []
        features = context.get("features", []) if context else []

        for i, feature in enumerate(features, 1):
            req = Requirement(
                id=f"REQ-{i:03d}",
                title=feature[:50],
                description=f"The system shall {feature.lower()}",
                type=RequirementType.UBIQUITOUS,
                priority=Priority.MEDIUM,
                acceptance_criteria=[
                    AcceptanceCriteria(
                        id=f"AC-{i:03d}-01",
                        description=f"Verify that {feature.lower()} works correctly"
                    )
                ],
            )
            requirements.append(req)

        # Create basic design
        design = DesignDoc(
            title=f"Design: {idea[:50]}",
            overview=idea,
            architecture="To be defined based on requirements analysis.",
            testing_strategy="Unit tests for core functionality, integration tests for APIs.",
        )

        # Create basic tasks
        tasks = []
        tasks.append(Task(
            id="TASK-001",
            title="Project Setup",
            description="Initialize project structure and dependencies",
            priority=Priority.HIGH,
        ))

        for i, req in enumerate(requirements, 2):
            tasks.append(Task(
                id=f"TASK-{i:03d}",
                title=f"Implement {req.title}",
                description=f"Implement functionality for: {req.description}",
                requirement_ids=[req.id],
                priority=req.priority,
            ))

        tasks.append(Task(
            id=f"TASK-{len(tasks)+1:03d}",
            title="Testing & Documentation",
            description="Write tests and documentation",
            priority=Priority.MEDIUM,
        ))

        task_list = TaskList(title=f"Tasks: {idea[:50]}", tasks=tasks)

        return Spec(
            name=idea[:100],
            description=idea,
            requirements=requirements,
            design=design,
            tasks=task_list,
        )

    def write_spec_files(
        self,
        spec: Spec,
        output_dir: str,
        create_kiro_structure: bool = True,
    ) -> dict:
        """Write spec files to disk.

        Args:
            spec: The spec to write
            output_dir: Base output directory
            create_kiro_structure: If True, create .kiro/specs/ structure

        Returns:
            Dict with file paths
        """
        from datetime import datetime

        base_path = Path(output_dir)

        if create_kiro_structure:
            # Create .kiro/specs/feature-name/ structure
            spec_name = spec.name.lower().replace(" ", "-")[:30]
            spec_name = "".join(c for c in spec_name if c.isalnum() or c == "-")
            spec_dir = base_path / ".kiro" / "specs" / spec_name
        else:
            spec_dir = base_path / "specs"

        spec_dir.mkdir(parents=True, exist_ok=True)

        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")
        files_written = {}

        # Write requirements.md
        requirements_md = ""
        for req in spec.requirements:
            requirements_md += req.to_markdown()

        requirements_content = REQUIREMENTS_TEMPLATE.format(
            name=spec.name,
            description=spec.description,
            requirements=requirements_md,
            timestamp=timestamp,
        )
        req_path = spec_dir / "requirements.md"
        req_path.write_text(requirements_content)
        files_written["requirements"] = str(req_path)

        # Write design.md
        if spec.design:
            design_content = DESIGN_TEMPLATE.format(
                name=spec.name,
                design_content=spec.design.to_markdown(),
                timestamp=timestamp,
            )
            design_path = spec_dir / "design.md"
            design_path.write_text(design_content)
            files_written["design"] = str(design_path)

        # Write tasks.md
        if spec.tasks:
            tasks_content = TASKS_TEMPLATE.format(
                name=spec.name,
                tasks_content=spec.tasks.to_markdown(),
                timestamp=timestamp,
            )
            tasks_path = spec_dir / "tasks.md"
            tasks_path.write_text(tasks_content)
            files_written["tasks"] = str(tasks_path)

        return {
            "spec_dir": str(spec_dir),
            "files": files_written,
            "spec": spec.to_dict(),
        }
